// Real-browser integration of the paired model comparison. Requires serve.py.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const path = require('path');
const fs = require('fs');

(async () => {
  const browser = await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'msedge'});
  const page = await browser.newPage({viewport:{width:1440,height:1150},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const output=path.resolve(process.env.UI_ARTIFACT_DIR||'artifacts/demo');
  fs.mkdirSync(output,{recursive:true});
  await page.goto(`${process.env.FORESIGHT_BASE_URL||'http://127.0.0.1:8765'}/web/compare.html`);
  await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('计算完成'));
  if(await page.locator('.method-card').count()!==4)throw new Error('Expected four synchronized methods');
  const nominal=await page.locator('.metric-value').allTextContents();
  if(nominal.some(value=>value.includes('—')))throw new Error('Missing prediction metrics');
  if(await page.locator('#seed').isVisible())throw new Error('Prediction seed incorrectly presented as a varying route');
  await page.screenshot({path:path.join(output,'comparison-prediction.png'),fullPage:true});
  await page.click('#reset');
  const initial=await page.locator('.metric-value').allTextContents();
  if(initial.some(value=>!value.startsWith('0.000')))throw new Error('Predictions do not share t0');
  await page.click('#play');
  await page.waitForFunction(()=>Number(document.querySelector('#timeline').value)>=5);
  await page.click('#play');
  const current=Number(await page.locator('#timeline').inputValue());
  if(current<5||current>16)throw new Error('Synchronized timeline failed');
  await page.selectOption('#condition','global_shift');
  await page.click('#run');
  await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('计算完成'));
  const shifted=await page.locator('.metric-value').allTextContents();
  await page.screenshot({path:path.join(output,'comparison-shift.png'),fullPage:true});
  await page.click('#field-evidence summary');
  await page.screenshot({path:path.join(output,'comparison-field.png'),fullPage:true});
  await page.selectOption('#action-mode','coast');
  await page.click('#run');
  await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('计算完成'));
  const coast=await page.locator('.metric-value').allTextContents();
  if(JSON.stringify(coast)===JSON.stringify(shifted))throw new Error('Action change did not change forecast');
  await page.selectOption('#action-mode','brake');
  await page.click('#run');
  await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('计算完成'));
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const canvasContent=await page.locator('.world-canvas').evaluateAll(canvases=>canvases.map(canvas=>{
    const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;
    return pixels.some((value,index)=>index%4===3&&value>0);
  }));
  if(canvasContent.some(painted=>!painted))throw new Error('A responsive canvas is blank');
  await page.screenshot({path:path.join(output,'comparison-mobile.png'),fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile comparison overflow');
  await page.setViewportSize({width:1440,height:1150});
  await page.click('[data-view="navigation"]');
  await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('生成完成'),null,{timeout:120000});
  const navigation=await page.locator('.metric-value').allTextContents();
  if(navigation.some(value=>!['抵达目标','发生碰撞','未在时限内抵达'].includes(value)))throw new Error('Missing navigation outcome');
  await page.screenshot({path:path.join(output,'comparison-navigation.png'),fullPage:true});
  await page.locator('#timeline').fill('10');
  await page.locator('#timeline').dispatchEvent('input');
  await page.screenshot({path:path.join(output,'comparison-navigation-running.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile navigation overflow');
  await browser.close();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log(JSON.stringify({ok:true,nominal,shifted,coast,navigation,pausedStep:current,browserErrors:errors,mobileOverflow:false}));
})().catch(error=>{console.error(error);process.exit(1);});
